name: Build modules

on:
  pull_request:

jobs:
  build_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.18
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build and test
        run: ./gradlew build